var DISQUS=function(c){var g=c.DISQUS||{};g.AssertionError=function(b){this.message=b};g.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};g.assert=function(b,d,f){if(!b)if(f)c.console&&c.console.log("DISQUS assertion failed: "+d);else throw new g.AssertionError(d);};var b=[];g.define=function(e,d){typeof e==="function"&&(d=e,e="");for(var f=e.split("."),h=f.shift(),a=g,l=(d||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},c);h;)a=a[h]?a[h]:a[h]={},h=f.shift();for(var j in l)l.hasOwnProperty(j)&&(!l.__overwrites__&&a[j]!==null&&g.assert(!a.hasOwnProperty(j),"Unsafe attempt to redefine existing module: "+j,!0),a[j]=l[j],b.push(function(a,b){return function(){delete a[b]}}(a,j)));return a};g.use=function(b){return g.define(b)};g.cleanup=function(){for(var e=0;e<b.length;e++)b[e]()};return g}(window);
DISQUS.define(function(c,g){var b=c.DISQUS,e=c.document,d=e.getElementsByTagName("head")[0]||e.body,f={running:!1,timer:null,queue:[]},h=0;b.getUid=function(a){var b=++h+"";return a?a+b:b};b.defer=function(a,b){function d(){var a=f.queue;if(a.length===0)f.running=!1,clearInterval(f.timer);for(var b=0,l;l=a[b];b++)l[0]()&&(a.splice(b--,1),l[1]())}f.queue.push([a,b]);d();if(!f.running)f.running=!0,f.timer=setInterval(d,100)};b.isOwn=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};b.isString=
function(a){return Object.prototype.toString.call(a)==="[object String]"};b.each=function(a,d){var f=a.length,h=Array.prototype.forEach;if(isNaN(f))for(var e in a)b.isOwn(a,e)&&d(a[e],e,a);else if(h)h.call(a,d);else for(h=0;h<f;h++)d(a[h],h,a)};b.extend=function(a){b.each(Array.prototype.slice.call(arguments,1),function(b){for(var d in b)a[d]=b[d]});return a};b.serializeArgs=function(a){var d=[];b.each(a,function(a,b){a!==g&&d.push(b+(a!==null?"="+encodeURIComponent(a):""))});return d.join("&")};
b.serialize=function(a,d,f){d&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=b.serializeArgs(d));if(f)return d={},d[(new Date).getTime()]=null,b.serialize(a,d);d=a.length;return a.charAt(d-1)=="&"?a.slice(0,d-1):a};b.require=function(a,f,h,c,g){function n(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))c&&c(),q&&clearTimeout(q),b.bean.remove(a.target,r,n)}var o=e.createElement("script"),r=o.addEventListener?"load":"readystatechange",q=null;o.src=b.serialize(a,f,
h);o.async=!0;o.charset="UTF-8";(c||g)&&b.bean.add(o,r,n);g&&(q=setTimeout(function(){g()},2E4));d.appendChild(o);return b};b.requireStylesheet=function(a,f,h){var c=e.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=b.serialize(a,f,h);d.appendChild(c);return b};b.requireSet=function(a,d,f){var h=a.length;b.each(a,function(a){b.require(a,{},d,function(){--h===0&&f()})})};b.injectCss=function(a){var b=e.createElement("style");b.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");
c.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));b.styleSheet?b.styleSheet.cssText=a:b.appendChild(e.createTextNode(a));d.appendChild(b)};b.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"}});
DISQUS.define("JSON",function(){function c(a){return a<10?"0"+a:a}function g(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(f,h){var c,e,k,n,j=a,p,i=h[f];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!d&&(i=i.toJSON(f));typeof m==="function"&&(i=m.call(h,f,i));switch(typeof i){case "string":return g(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";a+=l;p=[];if(Object.prototype.toString.apply(i)==="[object Array]"){n=i.length;for(c=0;c<n;c+=1)p[c]=b(c,i)||"null";k=p.length===0?"[]":a?"[\n"+a+p.join(",\n"+a)+"\n"+j+"]":"["+p.join(",")+"]";a=j;return k}if(m&&typeof m==="object"){n=m.length;for(c=0;c<n;c+=1)e=m[c],typeof e==="string"&&(k=b(e,i))&&p.push(g(e)+(a?": ":":")+k)}else for(e in i)Object.hasOwnProperty.call(i,e)&&(k=b(e,i))&&p.push(g(e)+(a?": ":":")+k);k=p.length===0?"{}":a?"{\n"+a+p.join(",\n"+a)+"\n"+
j+"}":"{"+p.join(",")+"}";a=j;return k}}var e={},d=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,l,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;e.stringify=function(d,f,h){var c;l=a="";if(typeof h==="number")for(c=0;c<h;c+=1)l+=" ";else typeof h==="string"&&(l=h);if((m=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return b("",{"":d})};e.parse=function(a,b){function d(a,
f){var h,c,e=a[f];if(e&&typeof e==="object")for(h in e)Object.hasOwnProperty.call(e,h)&&(c=d(e,h),c!==void 0?e[h]=c:delete e[h]);return b.call(a,f,e)}var h,a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+a+")"),
typeof b==="function"?d({"":h},""):h;throw new SyntaxError("JSON.parse");};var k={a:[1,2,3]},n,o;if(Object.toJSON&&Object.toJSON(k).replace(/\s/g,"")==='{"a":[1,2,3]}')n=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(k='{"a":[1,2,3]}'.evalJSON(),k.a&&k.a.length===3&&k.a[2]===3&&(o=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),d=!(a&&a.length===3&&a[2]===3))})();if(d||!n||!o)return{stringify:e.stringify,parse:e.parse};return{stringify:n,
parse:o}});
DISQUS.define("Bus",function(){function c(b){b=b.split("/");return b[0]+"//"+b[2]}var g=DISQUS.use("JSON"),b=window.location.hash.slice(1),e=window.opener||window.parent,d=document.referrer,f={};f.client=c(document.location.href);f.host=d?c(d):f.client;return{origins:f,messageHandler:function(b){var a;try{a=DISQUS.JSON.parse(b.data)}catch(d){return}if(!a.name||!(a.name[0]==="!"&&b.origin!==f.client))switch(a.scope){case "client":DISQUS.Bus.trigger(a.name,a.data)}},postMessage:function(d){d.sender=b;
d=g.stringify(d);e.postMessage(d,"*")},sendHostMessage:function(b,a){a=a||[];DISQUS.Bus.postMessage({scope:"host",name:b,data:a})},sendGlobalMessage:function(b,a){a=a||[];DISQUS.Bus.postMessage({scope:"global",name:b,data:a})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var c=window.addEventListener?window.addEventListener:window.attachEvent,g=window.addEventListener?"message":"onmessage";if(!c)throw Error("No event support.");c(g,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(){var c={apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)}};if(typeof require!=="undefined"&&typeof require==="function")c.bean=require("bean");return c});
DISQUS.define("strings",function(){function c(c){var d=b[c];return d!==void 0?d:c}function g(b,d){return b.replace(/%\(\w+\)s/g,function(f){var f=f.slice(2,-2),c="";f in d?c=d[f]!==void 0&&d[f]!==null?d[f].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+f+"` not found in context for: ",b);return c})}var b={};DISQUS.interpolate=g;DISQUS.modules={};window.gettext=c;return{get:c,interpolate:g,translations:b}});
DISQUS.define("time",function(){return{ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",assureTzOffset:function(c){return c.indexOf("+")>=0?c:c+"+00:00"}}});
DISQUS.define("urls",function(){var c=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",g=encodeURIComponent(document.referrer),b={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1373918630",translations:"http://mediacdn.disqus.com/1373918630/build/lang",loading:"http://mediacdn.disqus.com/1373918630/html/simple-loading.html",realertime:"",juggler:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
g,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1373918630/images/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1373918630"+c};window.location.protocol===
"https:"&&(b=_.extend(b,{root:"https://disqus.com",media:"https://securecdn.disqus.com/1373918630",translations:"https://securecdn.disqus.com/1373918630/build/lang",loading:"/html/simple-loading.html",api:b.apiSecure,logout:"https://disqus.com/logout/?redirect="+g,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},
avatar:{generic:"/images/noavatar92.png"},linkAffiliatorClient:""+c}));return b});DISQUS.define("templates",function(){function c(b,c){return Handlebars.partials[b](c||{},{data:g})}var g={urls:DISQUS.urls,gettext:DISQUS.strings.get,sso:null};DISQUS.renderBlock=c;DISQUS.templateGlobals=g;return{globals:g,render:c}});
DISQUS.define("api",function(){function c(b){function f(a){var g=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,g.length)===g&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId===c&&(g=a.code===0?b.success:b.error,delete a.requestId,(g||function(){})(a),document.body.removeChild(m),document.body.removeChild(e),$(window).off("message",f)))}var c=_.uniqueId("ft_"),a=document.createElement("div"),e=document.createElement("form"),g="frame_"+c,m;a.innerHTML='<iframe name="'+g+'"></iframe>';
m=a.childNodes[0];e.target=g;e.action=b.url.replace(".json",".pm");e.method=b.method||"GET";b.data=_.extend(b.data,{callback:c,referrer:document.referrer});_.each(b.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var d=document.createElement("input");d.type="hidden";d.name=b;d.value=a;e.appendChild(d)})});$(window).on("message",f);document.body.appendChild(m);document.body.appendChild(e);e.submit()}function g(d){d=_.defaults(d,b);if(!d.omitDisqusApiKey)d.data=
d.data||{},d.data.api_key=DISQUS.apiKey;return $.ajax(d)}var b={},e={defaults:function(d){var c,e,a;for(c in d)e=d[c],a=b[c],_.isObject(e)&&_.isObject(a)?_.extend(a,e):b[c]=e},headers:function(d){d=_.extend({},b.headers,d);b.headers=_.pick(d,_.map(d,function(b,d){if(b)return d}));return b.headers},getURL:function(b,c){c=c||{};if(c.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:g,call:function(b,e){e=e||{};e.url=DISQUS.api.getURL(b,{secure:e.secure});
e.data=_.extend(e.data||{},{api_key:DISQUS.apiKey});this.trigger("call",e);var h=(e.secure?c:g)(e);h&&h.always(_.bind(this.trigger,this,"complete"));return h}};_.extend(e,Backbone.Events);return e});
(function(c){var g=DISQUS.Bus,b=DISQUS.api.getURL("internal/switches/list.jsonp");c.switches_jsonp_cb=function(b){g.sendHostMessage("switches.received",b.response)};g.on("fetch",function(c){c=c||{};c.data=c.data||{};c.data.callback="switches_jsonp_cb";c.data.api_key=DISQUS.apiKey;c=DISQUS.serialize(b,c.data,!1);DISQUS.require(c)});g.sendHostMessage("ready")})(this);